/*
 * generated by Xtext 2.12.0
 */
package com.andredidier.multilingualtexteditor


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MultilingualTextEditorStandaloneSetup extends MultilingualTextEditorStandaloneSetupGenerated {

	def static void doSetup() {
		new MultilingualTextEditorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
