/*
 * generated by Xtext 2.12.0
 */
package com.andredidier.multilingualtexteditor.tests

import com.andredidier.multilingualtexteditor.multilingualTextEditor.Text
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(MultilingualTextEditorInjectorProvider)
class MultilingualTextEditorParsingTest {
	@Inject
	ParseHelper<Text> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
