/*
 * generated by Xtext 2.12.0
 */
package com.andredidier.multilingualtexteditor.ide


/**
 * Use this class to register ide components.
 */
class MultilingualTextEditorIdeModule extends AbstractMultilingualTextEditorIdeModule {
}
